- name: create an ec2 instance
  hosts: all
  connection: local
  vars:
    sg_id: "sg-0932cabd95603ae65"
    ami_id: "ami-0220d79f3f480ecf5"
    action: "create"
    env: "dev"
    # zone_id: "Z03858732HUVY50OKOZOA"
    domain: "ptdevops.online"
    instances:
      - mongodb
      - catalougue
      - redis
      - user
      - cart
      - mysql
      - payment
      - shipping
      - rabbitmq
      - frontend
  tasks:
    - name: creating multiple instances
      amazon.aws.ec2_instance:
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        name: "{{ item }}-{{ env }}"
        tags:
          project: roboshop
          environment: "{{ env }}"
          componenet: "{{ item }} "
          name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output
      when: action == "create"

    - name: getting the output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"

    - name: create route 53 reords
      amazon.aws.route53:
        state: present
        zone: "{{ domain }}"
        record: "{{ item.item }}-{{ env }}.{{ domain }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
      loop: "{{ ec2_output.results }}"
      when: action == "create"

    - name: create frontend route 53 reords
      amazon.aws.route53:
        state: present
        zone: "{{ domain }}"
        record: "roboshoop-{{ env }}.{{ domain }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
      loop: "{{ ec2_output.results }}"
      when:
        - item.item == "frontend"
        - action == "create"

      ### DESTROY ###
    - name: delete r53 records for frontend
      amazon.aws.route53:
        state: absent
        zone: "{{ domain }}"
        record: "roboshop-{{ env }}.{{ domain }}" # roboshop-dev.daws88s.online
        type: A
        ttl: 1
      loop: "{{ instances }}"
      when: # and
        - item == "frontend"
        - action == "destroy"

    - name: delete r53 records
      amazon.aws.route53:
        state: absent
        zone: "{{ domain }}"
        record: "{{ item }}-{{ env }}.{{ domain }}" # roboshop-dev.daws88s.online
        type: A
        ttl: 1
      loop: "{{ instances }}"
      when: action == "destroy"

    - name: delete ec2 instance
      amazon.aws.ec2_instance:
        state: absent
        name: "{{ item }}-{{ env }}"
        wait: false
      loop: "{{ instances }}"
      when: action == "destroy"
